#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/lib/docker-build.sh"
source "$ROOT_DIR/scripts/lib/docker-e2e-container.sh"
IMAGE_NAME="${MERCLAW_INSTALL_E2E_IMAGE:-merclaw-install-e2e:local}"
INSTALL_URL="${MERCLAW_INSTALL_URL:-https://merclaw.bot/install.sh}"
DOCKER_COMMAND_TIMEOUT="${DOCKER_COMMAND_TIMEOUT:-${MERCLAW_INSTALL_E2E_DOCKER_TIMEOUT:-2700s}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
MERCLAW_E2E_MODELS="${MERCLAW_E2E_MODELS:-}"

echo "==> Build image: $IMAGE_NAME"
docker_build_run install-e2e-build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker"

echo "==> Run E2E installer test"
docker_e2e_docker_run_cmd run --rm \
  -e MERCLAW_INSTALL_URL="$INSTALL_URL" \
  -e MERCLAW_INSTALL_TAG="${MERCLAW_INSTALL_TAG:-latest}" \
  -e MERCLAW_E2E_MODELS="$MERCLAW_E2E_MODELS" \
  -e MERCLAW_INSTALL_E2E_OPENAI_MODEL="${MERCLAW_INSTALL_E2E_OPENAI_MODEL:-}" \
  -e MERCLAW_INSTALL_E2E_OPENAI_PROVIDER_TIMEOUT_SECONDS="${MERCLAW_INSTALL_E2E_OPENAI_PROVIDER_TIMEOUT_SECONDS:-}" \
  -e MERCLAW_INSTALL_E2E_PREVIOUS="${MERCLAW_INSTALL_E2E_PREVIOUS:-}" \
  -e MERCLAW_INSTALL_E2E_SKIP_PREVIOUS="${MERCLAW_INSTALL_E2E_SKIP_PREVIOUS:-0}" \
  -e MERCLAW_INSTALL_E2E_AGENT_TURN_TIMEOUT_SECONDS="${MERCLAW_INSTALL_E2E_AGENT_TURN_TIMEOUT_SECONDS:-300}" \
  -e MERCLAW_INSTALL_E2E_AGENT_TURNS_PARALLEL="${MERCLAW_INSTALL_E2E_AGENT_TURNS_PARALLEL:-1}" \
  -e MERCLAW_INSTALL_E2E_AGENT_TOOL_SMOKE="${MERCLAW_INSTALL_E2E_AGENT_TOOL_SMOKE:-1}" \
  -e MERCLAW_NO_ONBOARD=1 \
  -e OPENAI_API_KEY \
  -e ANTHROPIC_API_KEY \
  -e ANTHROPIC_API_TOKEN \
  "$IMAGE_NAME"
