export const browserCoreExamples = [
  "merclaw browser status",
  "merclaw browser start",
  "merclaw browser start --headless",
  "merclaw browser stop",
  "merclaw browser tabs",
  "merclaw browser open https://example.com",
  "merclaw browser focus abcd1234",
  "merclaw browser close abcd1234",
  "merclaw browser screenshot",
  "merclaw browser screenshot --full-page",
  "merclaw browser screenshot --ref 12",
  "merclaw browser snapshot",
  "merclaw browser snapshot --format aria --limit 200",
  "merclaw browser snapshot --efficient",
  "merclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "merclaw browser navigate https://example.com",
  "merclaw browser resize 1280 720",
  "merclaw browser click 12 --double",
  "merclaw browser click-coords 120 340",
  'merclaw browser type 23 "hello" --submit',
  "merclaw browser press Enter",
  "merclaw browser hover 44",
  "merclaw browser drag 10 11",
  "merclaw browser select 9 OptionA OptionB",
  "merclaw browser upload /tmp/merclaw/uploads/file.pdf",
  "merclaw browser upload media://inbound/file.pdf",
  'merclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "merclaw browser dialog --accept",
  'merclaw browser wait --text "Done"',
  "merclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "merclaw browser console --level error",
  "merclaw browser pdf",
];
